/**
 * Server-side validation for customer design submissions.
 *
 * Everything here is pure and free of Supabase/Next imports so it can be unit
 * tested and so the API route never has to trust a single byte the customer
 * sent. The mobile page does its own light checks for UX only — this module is
 * the authority.
 */

import { isDesignType } from './types'
import type { DesignType, FlyerDetails } from './types'

/** Request ids are UUIDs generated by the server; nothing else is accepted. */
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/** Deliberately loose: enough to catch typos, not to police valid addresses. */
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export const MAX_LENGTHS = {
  business_name: 200,
  person_name: 120,
  job_title: 120,
  phone: 40,
  email: 200,
  website: 300,
  address: 300,
  social_media: 500,
  main_title: 200,
  description: 2000,
  additional_information: 2000,
  design_instructions: 2000,
} as const

export type ValidatedField = keyof typeof MAX_LENGTHS

/** Raw multipart text fields, before any trust is placed in them. */
export type RawSubmissionFields = Partial<Record<string, string>>

export interface ValidatedSubmission {
  design_type: DesignType
  business_name: string
  person_name: string | null
  job_title: string | null
  phone: string | null
  email: string | null
  website: string | null
  address: string | null
  social_media: string | null
  additional_information: string | null
  design_instructions: string | null
  flyer_details: FlyerDetails | null
}

export type ValidationResult =
  | { ok: true; value: ValidatedSubmission }
  | { ok: false; errors: string[]; fieldErrors: Record<string, string> }

/**
 * The only identifier in this system: the request id the server generates for
 * each submission. It is used in storage keys and to acknowledge a request, so
 * it is checked before it is ever concatenated into a path.
 */
export function isValidRequestId(value: unknown): value is string {
  return typeof value === 'string' && UUID_PATTERN.test(value)
}

/**
 * Strips NUL bytes and other control characters that have no business being in
 * a printed design, keeping newlines and tabs for the multi-line fields.
 */
export function sanitizeText(value: string): string {
  return value
    .replace(/\r\n?/g, '\n')
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, '')
    .trim()
}

function readField(
  raw: RawSubmissionFields,
  field: ValidatedField,
  fieldErrors: Record<string, string>
): string | null {
  const value = raw[field]
  if (typeof value !== 'string') return null

  const cleaned = sanitizeText(value)
  if (cleaned.length === 0) return null

  if (cleaned.length > MAX_LENGTHS[field]) {
    fieldErrors[field] = `Please keep this to ${MAX_LENGTHS[field]} characters or fewer.`
    return null
  }

  return cleaned
}

/**
 * Validates and normalises a customer submission.
 *
 * Business rules:
 *  - `design_type` must be one of the typed values, never a free-form string.
 *  - `business_name` is the only required field for both design types.
 *  - Flyer-only fields are collected into `flyer_details` and are left null for
 *    business cards, rather than being smeared across the shared columns.
 */
export function validateSubmission(raw: RawSubmissionFields): ValidationResult {
  const fieldErrors: Record<string, string> = {}

  const designTypeRaw = typeof raw.design_type === 'string' ? raw.design_type.trim() : ''
  if (!isDesignType(designTypeRaw)) {
    fieldErrors.design_type = 'Please choose a business card or a flyer.'
  }

  const businessNameRaw = typeof raw.business_name === 'string' ? sanitizeText(raw.business_name) : ''
  if (businessNameRaw.length === 0) {
    fieldErrors.business_name = 'Please enter your business name.'
  } else if (businessNameRaw.length > MAX_LENGTHS.business_name) {
    fieldErrors.business_name = `Please keep this to ${MAX_LENGTHS.business_name} characters or fewer.`
  }

  const person_name = readField(raw, 'person_name', fieldErrors)
  const job_title = readField(raw, 'job_title', fieldErrors)
  const phone = readField(raw, 'phone', fieldErrors)
  const email = readField(raw, 'email', fieldErrors)
  const website = readField(raw, 'website', fieldErrors)
  const address = readField(raw, 'address', fieldErrors)
  const social_media = readField(raw, 'social_media', fieldErrors)
  const additional_information = readField(raw, 'additional_information', fieldErrors)
  const design_instructions = readField(raw, 'design_instructions', fieldErrors)
  const main_title = readField(raw, 'main_title', fieldErrors)
  const description = readField(raw, 'description', fieldErrors)

  if (email && !EMAIL_PATTERN.test(email)) {
    fieldErrors.email = 'Please check this email address.'
  }

  if (phone && !/\d/.test(phone)) {
    fieldErrors.phone = 'Please check this phone number.'
  }

  const errors = Object.keys(fieldErrors)
  if (errors.length > 0) {
    return {
      ok: false,
      errors: errors.map((field) => fieldErrors[field]),
      fieldErrors,
    }
  }

  const design_type = designTypeRaw as DesignType

  return {
    ok: true,
    value: {
      design_type,
      business_name: businessNameRaw,
      person_name,
      job_title,
      phone,
      email,
      website,
      address,
      social_media,
      additional_information,
      design_instructions,
      flyer_details: design_type === 'flyer' ? { main_title, description } : null,
    },
  }
}
